from pathlib import Path

import joblib
from flask import Flask, render_template, request

BASE_DIR = Path(__file__).resolve().parent.parent
MODEL_PATH = BASE_DIR / "model" / "pipeline.joblib"
TRANSLATIONS = {
    "en": {
        "direction": "ltr",
        "page_title": "Heart Disease Prediction",
        "heading": "Heart Disease Prediction",
        "language_en": "English",
        "language_de": "Deutsch",
        "language_ar": "العربية",
        "age": "Age",
        "sex": "Sex",
        "cp": "Chest Pain Type",
        "trestbps": "Resting BP",
        "chol": "Cholesterol",
        "fbs": "Fasting Blood Sugar",
        "restecg": "Resting ECG",
        "thalach": "Max Heart Rate",
        "exang": "Exercise Angina",
        "oldpeak": "ST Depression",
        "slope": "Slope",
        "ca": "Major Vessels",
        "thal": "Thalassemia",
        "predict_button": "Predict",
        "result_label": "Result",
        "probability_label": "Risk Probability",
        "high_risk": "High Risk of Heart Disease",
        "low_risk": "Low Risk",
        "sex_select": "Choose sex",
        "sex_male": "Male",
        "sex_female": "Female",
        "cp_select": "Choose chest pain type",
        "cp_typical": "Typical Angina",
        "cp_atypical": "Atypical Angina",
        "cp_noanginal": "Non-Anginal Pain",
        "cp_asymp": "Asymptomatic",
        "fbs_select": "Choose fasting blood sugar level",
        "fbs_high": "> 120 mg/dl",
        "fbs_low": "≤ 120 mg/dl",
        "restecg_select": "Choose resting ECG result",
        "restecg_normal": "Normal",
        "restecg_stt": "ST-T Wave Abnormality",
        "restecg_hvh": "Left Ventricular Hypertrophy",
        "exang_select": "Choose",
        "exang_yes": "Yes",
        "exang_no": "No",
        "slope_select": "Choose slope",
        "slope_up": "Upsloping",
        "slope_flat": "Flat",
        "slope_down": "Downsloping",
        "thal_select": "Choose thalassemia type",
        "thal_normal": "Normal",
        "thal_fixed": "Fixed Defect",
        "thal_reversible": "Reversible Defect",
        "hint_sex": "Select your gender",
        "hint_age": "Enter your age in years (29-77)",
        "hint_cp": "Choose the type of chest pain you experience",
        "hint_trestbps": "Resting blood pressure in mm Hg",
        "hint_chol": "Serum cholesterol in mg/dl",
        "hint_fbs": "Based on your fasting blood sugar test",
        "hint_restecg": "Result from your resting electrocardiogram",
        "hint_thalach": "Maximum heart rate achieved during exercise",
        "hint_exang": "Do you experience chest pain with exercise?",
        "hint_oldpeak": "ST depression induced by exercise (0-6.2)",
        "hint_slope": "Slope of ST segment during exercise",
        "hint_ca": "Number of major vessels visible (0-4)",
        "hint_thal": "Thalassemia type from imaging",
        "help_button": "How to fill this form?",
        "help_text": "Fill in the medical values as they appear in your medical report. For fields with dropdown arrows, select from the options. If you don't understand a field, click the ⓘ icon next to it for more details. Don't enter random values—use your actual medical data.",
        "important_note_title": "Important Information",
        "important_note_text": "Some fields in this form require a medical report or cardiac test results. If you don't know what a field means, click the ⓘ icon next to it. Do not enter random values - accuracy depends on your actual medical data.",
        "what_is": "What is this?",
        "what_to_select": "What to select?",
        "what_to_write": "What to write?",
        "where_to_find": "Where to find this information?",
        "medical_required": "⚠️ Requires a medical report or specialist test",
        "info_sex_what": "The biological sex of the patient.",
        "info_sex_select": "Choose Male or Female from the list.",
        "info_sex_source": "From the patient's basic information.",
        "info_age_what": "The age of the patient in years.",
        "info_age_write": "Enter the age as a number, for example: 45.",
        "info_age_source": "From the patient's actual age.",
        "info_cp_what": "Describes the type of chest pain the patient experiences.",
        "info_cp_select": "Choose the description closest to the patient's condition: Typical Angina, Atypical Angina, Non-Anginal Pain, or Asymptomatic.",
        "info_cp_source": "From the patient's complaint or the doctor's description in the medical report.",
        "info_trestbps_what": "Resting blood pressure in mm Hg.",
        "info_trestbps_write": "Enter the number only, for example: 120 or 130.",
        "info_trestbps_source": "From a blood pressure measurement device or test report.",
        "info_chol_what": "The level of cholesterol in the blood in mg/dl.",
        "info_chol_write": "Enter the test value as it appears, for example: 240.",
        "info_chol_source": "From a blood test or laboratory report.",
        "info_fbs_what": "Whether the patient's fasting blood sugar is greater than 120 mg/dl.",
        "info_fbs_select": "If the test result is greater than 120, choose the first option. If it's 120 or less, choose the second option.",
        "info_fbs_source": "From a fasting blood sugar test or laboratory report.",
        "info_restecg_what": "The result of an electrocardiogram taken at rest.",
        "info_restecg_select": "Choose the result closest to what's written in the report: Normal, ST-T Wave Abnormality, or Left Ventricular Hypertrophy.",
        "info_restecg_source": "From an ECG/EKG report or doctor's medical report.",
        "info_thalach_what": "The highest heart rate the patient achieved during exercise or stress testing.",
        "info_thalach_write": "Enter the number only, for example: 150.",
        "info_thalach_source": "From a stress test or medical report.",
        "info_exang_what": "Whether the patient experiences chest pain or angina when exercising or exerting effort.",
        "info_exang_select": "Choose Yes if pain appears with movement or effort. Choose No if this doesn't happen.",
        "info_exang_source": "From the patient's description or doctor's medical report.",
        "info_oldpeak_what": "The ST depression value during exercise compared to rest.",
        "info_oldpeak_write": "Enter the value as it appears in the report, for example: 1.5 or 2.0.",
        "info_oldpeak_source": "From a stress test or cardiac report.",
        "info_slope_what": "The shape of the ST segment during stress: Upsloping, Flat, or Downsloping.",
        "info_slope_select": "Choose the shape written in the medical report.",
        "info_slope_source": "From a stress test or doctor's medical report.",
        "info_ca_what": "The number of major blood vessels visible or highlighted on cardiac imaging.",
        "info_ca_write": "Enter the number as it appears in the report, for example: 0, 1, or 2.",
        "info_ca_source": "From a cardiac catheterization or specialized cardiac test report.",
        "info_thal_what": "The result of a thalassemia test related to blood perfusion or cardiac defect status.",
        "info_thal_select": "Choose: Normal, Fixed Defect, or Reversible Defect.",
        "info_thal_source": "From a cardiac imaging test or doctor's specialist report.",
        "info_sex": "Select your biological sex: Male = Man, Female = Woman.",
        "info_age": "Enter your current age in years. The values in this model range from 29 to 77.",
        "info_cp": "Choose the type of chest pain: Typical Angina = clear heart-related pain, Atypical Angina = similar to heart pain but not typical, Non-Anginal Pain = pain usually not from the heart, Asymptomatic = no obvious pain.",
        "info_trestbps": "This is your resting blood pressure in mm Hg. You can get this value from your medical report or blood pressure measurement.",
        "info_chol": "Enter your serum cholesterol level in mg/dl. This value is from your blood test report.",
        "info_fbs": "This field indicates whether your fasting blood sugar is greater than 120 mg/dl. Choose based on your test results.",
        "info_restecg": "Choose the result closest to your electrocardiogram: Normal = no apparent abnormality, ST-T Wave Abnormality = unusual changes in the ECG, Left Ventricular Hypertrophy = thickening of the left heart muscle.",
        "info_thalach": "Enter the maximum heart rate you achieved during exercise testing. This value is from your cardiac test report.",
        "info_exang": "Do you experience chest pain or angina when exercising or using effort? Choose Yes or No.",
        "info_oldpeak": "This is the ST depression value from your cardiac test. It represents how much the ST segment drops during exercise. If you don't know it, get it from your medical report.",
        "info_slope": "This describes the shape of the ST segment under stress: Upsloping, Flat, or Downsloping. Choose based on your test results.",
        "info_ca": "This is the number of major blood vessels visible in your cardiac imaging. Usually between 0 and 4.",
        "info_thal": "This field is related to thalassemia test results: Normal = no abnormality, Fixed Defect = permanent defect, Reversible Defect = defect that may vary.",
        "validation_error": "Please fill in all required fields correctly before submitting.",
        "result_intro": "Preliminary Result:",
        "result_probability": "Risk Assessment:",
        "result_disclaimer": "⚠️ This result is NOT a final medical diagnosis. It's an estimate based on the data you entered.",
        "result_recommendation": "Recommended next step: Consult a doctor or compare these values with your medical report.",
        "reset_button": "Reset Form",
        "sample_values": "Use Sample Values",
        "source_blood_test": "From blood test",
        "source_ecg": "From ECG report",
        "source_stress_test": "From stress test",
        "source_specialist": "From specialist report",
        "risk_level_low": "Low Risk",
        "risk_level_medium": "Moderate Risk",
        "risk_level_high": "High Risk",
    },
    "de": {
        "direction": "ltr",
        "page_title": "Herzerkrankungs-Prognose",
        "heading": "Herzerkrankungs-Prognose",
        "language_en": "English",
        "language_de": "Deutsch",
        "language_ar": "العربية",
        "age": "Alter",
        "sex": "Geschlecht",
        "cp": "Brustschmerztyp",
        "trestbps": "Ruheblutdruck",
        "chol": "Cholesterin",
        "fbs": "Nüchternblutzucker",
        "restecg": "Ruhe-EKG",
        "thalach": "Max Herzfrequenz",
        "exang": "Belastungsangina",
        "oldpeak": "ST-Senkung",
        "slope": "Steigung",
        "ca": "Major Arterien",
        "thal": "Thalassämie",
        "predict_button": "Vorhersagen",
        "result_label": "Ergebnis",
        "probability_label": "Risikowahrscheinlichkeit",
        "high_risk": "Hohes Risiko für Herzerkrankung",
        "low_risk": "Niedriges Risiko",
        "sex_select": "Geschlecht wählen",
        "sex_male": "Männlich",
        "sex_female": "Weiblich",
        "cp_select": "Brustschmerztyp wählen",
        "cp_typical": "Typische Angina",
        "cp_atypical": "Atypische Angina",
        "cp_noanginal": "Nicht-anginöse Schmerzen",
        "cp_asymp": "Asymptomatisch",
        "fbs_select": "Nüchternblutzucker wählen",
        "fbs_high": "> 120 mg/dl",
        "fbs_low": "≤ 120 mg/dl",
        "restecg_select": "Ruhe-EKG-Ergebnis wählen",
        "restecg_normal": "Normal",
        "restecg_stt": "ST-T-Wellen-Anomalie",
        "restecg_hvh": "Linksventrikuläre Hypertrophie",
        "exang_select": "Wählen",
        "exang_yes": "Ja",
        "exang_no": "Nein",
        "slope_select": "Steigung wählen",
        "slope_up": "Ansteigend",
        "slope_flat": "Flach",
        "slope_down": "Absteigend",
        "thal_select": "Thalassämie-Typ wählen",
        "thal_normal": "Normal",
        "thal_fixed": "Festgestellter Defekt",
        "thal_reversible": "Reversibler Defekt",
        "hint_sex": "Wählen Sie Ihr Geschlecht",
        "hint_age": "Geben Sie Ihr Alter in Jahren ein (29-77)",
        "hint_cp": "Wählen Sie die Art der Brustschmerzen",
        "hint_trestbps": "Ruheblutdruck in mm Hg",
        "hint_chol": "Serumcholesterin in mg/dl",
        "hint_fbs": "Basierend auf Ihrem Nüchternbluttest",
        "hint_restecg": "Ergebnis aus Ihrem Ruhe-EKG",
        "hint_thalach": "Maximale Herzfrequenz erreicht während Bewegung",
        "hint_exang": "Verspüren Sie Brustschmerzen bei Anstrengung?",
        "hint_oldpeak": "ST-Senkung durch Belastung (0-6.2)",
        "hint_slope": "Steigung des ST-Segments während Belastung",
        "hint_ca": "Anzahl der sichtbaren Arterien (0-4)",
        "hint_thal": "Thalassämie-Typ aus Bildgebung",
        "help_button": "Wie fülle ich dieses Formular aus?",
        "help_text": "Füllen Sie die medizinischen Werte aus, wie sie in Ihrem Bericht stehen. Für Felder mit Dropdown-Pfeilen wählen Sie aus den Optionen. Wenn Sie ein Feld nicht verstehen, klicken Sie auf das ⓘ-Symbol daneben. Geben Sie keine zufälligen Werte ein.",
        "important_note_title": "Wichtige Information",
        "important_note_text": "Einige Felder in diesem Formular erfordern einen ärztlichen Bericht oder Herztest-Ergebnisse. Wenn Sie nicht verstehen, was ein Feld bedeutet, klicken Sie auf das ⓘ-Symbol daneben. Geben Sie keine zufälligen Werte ein - die Genauigkeit hängt von Ihren echten medizinischen Daten ab.",
        "what_is": "Was ist das?",
        "what_to_select": "Was soll ich wählen?",
        "what_to_write": "Was soll ich schreiben?",
        "where_to_find": "Wo finde ich diese Information?",
        "medical_required": "⚠️ Benötigt einen ärztlichen Bericht oder Fachtest",
        "info_sex_what": "Das biologische Geschlecht des Patienten.",
        "info_sex_select": "Wählen Sie Männlich oder Weiblich aus der Liste.",
        "info_sex_source": "Aus den Grundinformationen des Patienten.",
        "info_age_what": "Das Alter des Patienten in Jahren.",
        "info_age_write": "Geben Sie das Alter als Zahl ein, zum Beispiel: 45.",
        "info_age_source": "Aus dem tatsächlichen Alter des Patienten.",
        "info_cp_what": "Beschreibt die Art des Brustschmerzes, den der Patient erfährt.",
        "info_cp_select": "Wählen Sie die Beschreibung, die dem Zustand des Patienten am nächsten kommt: Typische Angina, Atypische Angina, Nicht-anginöse Schmerzen oder Asymptomatisch.",
        "info_cp_source": "Aus der Beschwerde des Patienten oder der Beschreibung des Arztes im Bericht.",
        "info_trestbps_what": "Der Ruheblutdruck in mm Hg.",
        "info_trestbps_write": "Geben Sie nur die Zahl ein, zum Beispiel: 120 oder 130.",
        "info_trestbps_source": "Von einem Blutdruckmessgerät oder Testbericht.",
        "info_chol_what": "Der Cholesterinspiegel im Blut in mg/dl.",
        "info_chol_write": "Geben Sie den Testwert ein, wie er angezeigt wird, zum Beispiel: 240.",
        "info_chol_source": "Von einem Bluttest oder Laborbericht.",
        "info_fbs_what": "Ob der Nüchternblutzucker des Patienten höher als 120 mg/dl ist.",
        "info_fbs_select": "Wenn der Testwert höher als 120 ist, wählen Sie die erste Option. Wenn er 120 oder weniger ist, wählen Sie die zweite.",
        "info_fbs_source": "Von einem Nüchternbluttest oder Laborbericht.",
        "info_restecg_what": "Das Ergebnis eines Elektrokardiogramms in Ruhe.",
        "info_restecg_select": "Wählen Sie das Ergebnis, das dem ähnlichsten im Bericht entspricht: Normal, ST-T-Anomalie oder Linksventrikuläre Hypertrophie.",
        "info_restecg_source": "Von einem EKG-Bericht oder ärztlichen Bericht.",
        "info_thalach_what": "Die höchste Herzfrequenz, die der Patient während Belastungsprüfung erreicht hat.",
        "info_thalach_write": "Geben Sie nur die Zahl ein, zum Beispiel: 150.",
        "info_thalach_source": "Von einem Belastungstest oder ärztlichem Bericht.",
        "info_exang_what": "Ob der Patient Brustschmerzen oder Angina verspürt, wenn er trainiert oder sich anstrengt.",
        "info_exang_select": "Wählen Sie Ja, wenn Schmerzen bei Bewegung oder Anstrengung auftreten. Wählen Sie Nein, wenn nicht.",
        "info_exang_source": "Aus der Beschreibung des Patienten oder dem ärztlichen Bericht.",
        "info_oldpeak_what": "Der ST-Senkungswert während Belastung im Vergleich zu Ruhe.",
        "info_oldpeak_write": "Geben Sie den Wert ein, wie er im Bericht angezeigt wird, zum Beispiel: 1.5 oder 2.0.",
        "info_oldpeak_source": "Von einem Belastungstest oder Herzbericht.",
        "info_slope_what": "Die Form des ST-Segments unter Stress: Ansteigend, Flach oder Absteigend.",
        "info_slope_select": "Wählen Sie die im Bericht geschriebene Form.",
        "info_slope_source": "Von einem Belastungstest oder ärztlichem Bericht.",
        "info_ca_what": "Die Anzahl der großen Blutgefäße in der Herzbildgebung.",
        "info_ca_write": "Geben Sie die Zahl ein, wie sie im Bericht angezeigt wird, zum Beispiel: 0, 1 oder 2.",
        "info_ca_source": "Von einem Herzkatheter oder spezialisiertem Herzbericht.",
        "info_thal_what": "Das Ergebnis eines Thalassämie-Tests.",
        "info_thal_select": "Wählen Sie: Normal, Festgestellter Defekt oder Reversibler Defekt.",
        "info_thal_source": "Von einem Herzbild-Test oder Facharztbericht.",
        "info_sex": "Wählen Sie Ihr biologisches Geschlecht: Männlich = Mann, Weiblich = Frau.",
        "info_age": "Geben Sie Ihr aktuelles Alter in Jahren ein. Die Werte in diesem Modell liegen zwischen 29 und 77.",
        "info_cp": "Wählen Sie die Art der Brustschmerzen: Typische Angina = klarer herzabhängiger Schmerz, Atypische Angina = ähnlich wie Herzschmerz, aber nicht typisch, Nicht-anginöse Schmerzen = Schmerzen, die normalerweise nicht vom Herzen stammen, Asymptomatisch = kein offensichtlicher Schmerz.",
        "info_trestbps": "Dies ist Ihr Ruheblutdruck in mm Hg. Sie können diesen Wert aus Ihrem Bericht oder Blutdruckmessung abrufen.",
        "info_chol": "Geben Sie Ihren Serumcholesterinwert in mg/dl ein. Dieser Wert stammt aus Ihrem Bluttestbericht.",
        "info_fbs": "Dieses Feld gibt an, ob Ihr Nüchternblutzucker höher als 120 mg/dl ist. Wählen Sie basierend auf Ihren Testergebnissen.",
        "info_restecg": "Wählen Sie das Ergebnis, das Ihrem EKG am nächsten kommt: Normal = keine offensichtliche Anomalie, ST-T-Wellen-Anomalie = ungewöhnliche Veränderungen, Linksventrikuläre Hypertrophie = Verdickung der Herzmuskulatur.",
        "info_thalach": "Geben Sie die maximale Herzfrequenz ein, die Sie während der Belastungsprüfung erreicht haben.",
        "info_exang": "Verspüren Sie bei Belastung oder Anstrengung Brustschmerzen? Wählen Sie Ja oder Nein.",
        "info_oldpeak": "Dies ist der ST-Senkungswert aus Ihrem Herztest.",
        "info_slope": "Dies beschreibt die Form des ST-Segments unter Stress: Ansteigend, Flach oder Absteigend.",
        "info_ca": "Dies ist die Anzahl der Blutgefäße in Ihrem Herzbildgebung.",
        "info_thal": "Dieses Feld bezieht sich auf Thalassämie-Testergebnisse: Normal, Festgestellter Defekt oder Reversibler Defekt.",
        "validation_error": "Bitte füllen Sie alle erforderlichen Felder korrekt aus, bevor Sie das Formular einreichen.",
        "result_intro": "Vorläufiges Ergebnis:",
        "result_probability": "Risikobewertung:",
        "result_disclaimer": "⚠️ Dieses Ergebnis ist KEINE endgültige medizinische Diagnose. Es ist eine Schätzung basierend auf den eingegebenen Daten.",
        "result_recommendation": "Empfohlener nächster Schritt: Konsultieren Sie einen Arzt oder vergleichen Sie diese Werte mit Ihrem medizinischen Bericht.",
        "reset_button": "Formular zurücksetzen",
        "sample_values": "Beispielwerte verwenden",
        "source_blood_test": "Aus Bluttest",
        "source_ecg": "Aus EKG-Bericht",
        "source_stress_test": "Aus Belastungstest",
        "source_specialist": "Aus Facharztbericht",
        "risk_level_low": "Niedriges Risiko",
        "risk_level_medium": "Mittleres Risiko",
        "risk_level_high": "Hohes Risiko",
    },
    "ar": {
        "direction": "rtl",
        "page_title": "التنبؤ بأمراض القلب",
        "heading": "التنبؤ بأمراض القلب",
        "language_en": "الإنجليزية",
        "language_de": "الألمانية",
        "language_ar": "العربية",
        "age": "العمر",
        "sex": "الجنس",
        "cp": "نوع ألم الصدر",
        "trestbps": "ضغط الدم أثناء الراحة",
        "chol": "الكوليسترول",
        "fbs": "سكر الدم الصائم",
        "restecg": "تخطيط القلب أثناء الراحة",
        "thalach": "أقصى معدل لنبض القلب",
        "exang": "ذبحة صدرية مع المجهود",
        "oldpeak": "الانخفاض ST",
        "slope": "الميل",
        "ca": "عدد الأوعية الرئيسية",
        "thal": "الثال",
        "predict_button": "توقع النتيجة",
        "result_label": "النتيجة",
        "probability_label": "احتمال الخطورة",
        "high_risk": "خطر مرتفع للإصابة بمرض القلب",
        "low_risk": "خطر منخفض",
        "sex_select": "اختر الجنس",
        "sex_male": "ذكر",
        "sex_female": "أنثى",
        "cp_select": "اختر نوع ألم الصدر",
        "cp_typical": "ذبحة صدرية نموذجية",
        "cp_atypical": "ذبحة صدرية غير نموذجية",
        "cp_noanginal": "ألم غير ذبحي",
        "cp_asymp": "بدون أعراض",
        "fbs_select": "اختر مستوى سكر الدم الصائم",
        "fbs_high": "أكبر من 120 ملغ/ديسيلتر",
        "fbs_low": "120 ملغ/ديسيلتر أو أقل",
        "restecg_select": "اختر نتيجة تخطيط القلب",
        "restecg_normal": "طبيعي",
        "restecg_stt": "اضطراب موجة ST-T",
        "restecg_hvh": "تضخم البطين الأيسر",
        "exang_select": "اختر",
        "exang_yes": "نعم",
        "exang_no": "لا",
        "slope_select": "اختر الميل",
        "slope_up": "صاعد",
        "slope_flat": "مسطح",
        "slope_down": "هابط",
        "thal_select": "اختر نوع الثال",
        "thal_normal": "طبيعي",
        "thal_fixed": "عيب ثابت",
        "thal_reversible": "عيب قابل للعكس",
        "hint_sex": "اختر الجنس من القائمة",
        "hint_age": "أدخل العمر بالسنوات (29-77)",
        "hint_cp": "اختر الوصف الأقرب لنوع الألم الذي تشعر به",
        "hint_trestbps": "يكتب بوحدة mm Hg",
        "hint_chol": "أدخل قيمة الكوليسترول في الدم",
        "hint_fbs": "اختر القيمة المناسبة بناءً على التحليل",
        "hint_restecg": "اختر النتيجة الأقرب من التقرير الطبي",
        "hint_thalach": "أدخل أعلى معدل نبض تم الوصول إليه",
        "hint_exang": "هل يظهر ألم صدري عند الجهد؟",
        "hint_oldpeak": "أدخل قيمة ST depression",
        "hint_slope": "اختر شكل انحدار ST أثناء الجهد",
        "hint_ca": "عدد الأوعية الرئيسية الملونة بالفحص",
        "hint_thal": "اختر الحالة حسب نتيجة الفحص",
        "help_button": "كيف أملأ هذا النموذج؟",
        "help_text": "املأ القيم الطبية كما هي في التقرير الطبي. الحقول التي تحتوي على سهم هي قوائم اختيار. إذا لم تفهم معنى أي حقل، اضغط على الرمز ⓘ بجانب اسم الحقل. لا تدخل قيماً عشوائية - استخدم بيانات طبية فعلية.",
        "important_note_title": "معلومة مهمة:",
        "important_note_text": "بعض الحقول في هذا النموذج تحتاج إلى تقرير طبي أو نتائج فحوصات قلبية. إذا لم تفهم معنى أي حقل، اضغط على الرمز ⓘ بجانب الحقل. لا تدخل قيماً عشوائية - دقة النتيجة تعتمد على بيانات طبية فعلية.",
        "what_is": "ما هو هذا؟",
        "what_to_select": "ماذا أختار؟",
        "what_to_write": "ماذا أكتب؟",
        "where_to_find": "من أين أجد هذه المعلومة؟",
        "medical_required": "⚠️ يتطلب تقريراً طبياً أو فحصاً متخصصاً",
        "info_sex_what": "الجنس البيولوجي للمريض.",
        "info_sex_select": "اختر ذكر أو أنثى من القائمة.",
        "info_sex_source": "من بيانات المريض الأساسية.",
        "info_age_what": "عمر المريض بالسنوات.",
        "info_age_write": "أدخل العمر كرقم فقط، مثل: 45.",
        "info_age_source": "من العمر الحقيقي للمريض.",
        "info_cp_what": "يصف نوع الألم الذي يشعر به المريض في الصدر.",
        "info_cp_select": "اختر الوصف الأقرب لحالة المريض: ذبحة نموذجية، غير نموذجية، ألم غير ذبحي، أو بدون أعراض.",
        "info_cp_source": "من شكوى المريض أو وصف الطبيب في التقرير الطبي.",
        "info_trestbps_what": "ضغط الدم أثناء الراحة بوحدة mm Hg.",
        "info_trestbps_write": "أدخل الرقم فقط، مثل: 120 أو 130.",
        "info_trestbps_source": "من جهاز قياس الضغط أو تقرير الفحص.",
        "info_chol_what": "مستوى الكوليسترول في الدم بوحدة mg/dl.",
        "info_chol_write": "أدخل قيمة التحليل كما هي، مثل: 240.",
        "info_chol_source": "من تحليل الدم أو تقرير المختبر.",
        "info_fbs_what": "هل سكر الدم الصائم أكبر من 120 mg/dl أم لا.",
        "info_fbs_select": "إذا كانت النتيجة أعلى من 120 اختر الخيار الأول، وإذا كانت 120 أو أقل اختر الخيار الثاني.",
        "info_fbs_source": "من تحليل سكر الدم الصائم أو تقرير المختبر.",
        "info_restecg_what": "نتيجة تخطيط القلب أثناء الراحة.",
        "info_restecg_select": "اختر النتيجة الأقرب المكتوبة في التقرير: طبيعي، اضطراب ST-T، أو تضخم البطين الأيسر.",
        "info_restecg_source": "من تقرير ECG/EKG أو من تقرير الطبيب.",
        "info_thalach_what": "أعلى معدل نبض وصل إليه المريض أثناء الفحص أو الجهد.",
        "info_thalach_write": "أدخل الرقم فقط، مثل: 150.",
        "info_thalach_source": "من اختبار الجهد أو التقرير الطبي.",
        "info_exang_what": "هل يظهر ألم أو ذبحة صدرية عند بذل الجهد؟",
        "info_exang_select": "اختر نعم إذا كان الألم يظهر مع الحركة أو الجهد، واختر لا إذا لم يحدث ذلك.",
        "info_exang_source": "من وصف المريض أو من تقرير الطبيب.",
        "info_oldpeak_what": "قيمة ST depression أثناء الجهد مقارنة بالراحة.",
        "info_oldpeak_write": "أدخل القيمة كما هي في التقرير، مثل: 1.5 أو 2.0.",
        "info_oldpeak_source": "من اختبار الجهد أو تقرير القلب.",
        "info_slope_what": "شكل انحدار ST أثناء الجهد: صاعد، مسطح، أو هابط.",
        "info_slope_select": "اختر الشكل المكتوب في التقرير الطبي.",
        "info_slope_source": "من اختبار الجهد أو تقرير الطبيب.",
        "info_ca_what": "عدد الأوعية الرئيسية الظاهرة أو الملونة بالفحص.",
        "info_ca_write": "أدخل الرقم كما هو في التقرير، مثل: 0 أو 1 أو 2.",
        "info_ca_source": "من تقرير القسطرة أو الفحص القلبي المتخصص.",
        "info_thal_what": "نتيجة فحص thal المتعلقة بحالة التروية أو العيب القلبي.",
        "info_thal_select": "اختر: طبيعي، عيب ثابت، أو عيب قابل للعكس.",
        "info_thal_source": "من تقرير الفحص الطبي أو تقرير الطبيب المختص.",
        "info_sex": "اختر الجنس البيولوجي: ذكر = رجل، أنثى = امرأة.",
        "info_age": "أدخل عمرك الحالي بالسنوات. القيم في هذا النموذج تتراوح بين 29 و 77 سنة.",
        "info_cp": "اختر نوع ألم الصدر: ذبحة نموذجية = ألم واضح مرتبط بالقلب، ذبحة غير نموذجية = ألم يشبه ألم القلب لكنه ليس نمطياً، ألم غير ذبحي = ألم غالباً ليس من القلب، بدون أعراض = لا يوجد ألم واضح.",
        "info_trestbps": "هذا ضغط دمك أثناء الراحة بوحدة mm Hg. يمكنك الحصول على هذه القيمة من التقرير الطبي أو قياس ضغط الدم.",
        "info_chol": "أدخل قيمة الكوليسترول في الدم بوحدة mg/dl. تأتي هذه القيمة من تقرير فحص الدم.",
        "info_fbs": "هذا الحقل يعني: هل سكر الدم الصائم أكبر من 120 mg/dl؟ اختر بناءً على نتائج التحليل.",
        "info_restecg": "اختر النتيجة الأقرب من تقرير تخطيط القلب: طبيعي = لا يوجد خلل ظاهر، اضطراب ST-T = تغيرات غير طبيعية، تضخم البطين الأيسر = زيادة في سماكة عضلة البطين الأيسر.",
        "info_thalach": "أدخل أعلى معدل نبض تم الوصول إليه أثناء اختبار الجهد. هذه القيمة من تقرير فحص القلب.",
        "info_exang": "هل تشعر بألم صدري أو ذبحة عند بذل الجهد أو الحركة؟ اختر نعم أو لا.",
        "info_oldpeak": "هذه قيمة من تقرير الفحص القلبي وتمثل مقدار انخفاض ST أثناء الجهد. إذا كنت لا تعرفها، خذها من التقرير الطبي.",
        "info_slope": "هذا يصف شكل انحدار ST أثناء الجهد: صاعد، مسطح، أو هابط. اختره حسب نتيجة الفحص.",
        "info_ca": "هذا الرقم يعبر عن عدد الأوعية الرئيسية التي ظهرت في الفحص. غالباً تكون القيمة بين 0 و 4.",
        "info_thal": "هذا الحقل مرتبط بنتيجة فحص thal: طبيعي = لا يوجد خلل، عيب ثابت = خلل ثابت، عيب قابل للعكس = خلل يظهر ويمكن أن يتغير.",
        "validation_error": "يرجى ملء جميع الحقول المطلوبة بشكل صحيح قبل الإرسال.",
        "result_intro": "النتيجة الأولية:",
        "result_probability": "تقييم الخطورة:",
        "result_disclaimer": "⚠️ هذه النتيجة ليست تشخيصاً طبياً نهائياً. إنها تقدير مبني على البيانات التي أدخلتها.",
        "result_recommendation": "الخطوة المقترحة: استشر طبيباً أو قارن هذه القيم مع التقرير الطبي.",
        "reset_button": "إعادة تعيين النموذج",
        "sample_values": "استخدم قيماً نموذجية",
        "source_blood_test": "من تحليل الدم",
        "source_ecg": "من تقرير تخطيط القلب",
        "source_stress_test": "من اختبار الجهد",
        "source_specialist": "من تقرير الطبيب المختص",
        "risk_level_low": "خطر منخفض",
        "risk_level_medium": "خطر متوسط",
        "risk_level_high": "خطر مرتفع",
    },
}

app = Flask(
    __name__,
    template_folder=str(BASE_DIR / "templates"),
    static_folder=str(BASE_DIR / "static"),
)
model = joblib.load(MODEL_PATH)


def get_language(value):
    return value if value in TRANSLATIONS else "en"


@app.route("/")
def home():
    lang = get_language(request.args.get("lang", "en"))
    return render_template(
        "index.html",
        prediction=None,
        probability=None,
        lang=lang,
        text=TRANSLATIONS[lang],
    )


@app.route("/predict", methods=["POST"])
def predict():
    lang = get_language(request.form.get("lang", "en"))
    text = TRANSLATIONS[lang]
    
    # Extract and convert form data to numeric values
    age = int(request.form["age"])
    sex = int(request.form["sex"])
    cp = int(request.form["cp"])
    trestbps = int(request.form["trestbps"])
    chol = int(request.form["chol"])
    fbs = int(request.form["fbs"])
    restecg = int(request.form["restecg"])
    thalach = int(request.form["thalach"])
    exang = int(request.form["exang"])
    oldpeak = float(request.form["oldpeak"])
    slope = int(request.form["slope"])
    ca = int(request.form["ca"])
    thal = int(request.form["thal"])
    
    # Create feature vector
    features = [[age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal]]
    
    prediction = model.predict(features)[0]
    probability = model.predict_proba(features)[0][1]

    if prediction == 1:
        result = text["high_risk"]
    else:
        result = text["low_risk"]

    return render_template(
        "index.html",
        prediction=result,
        probability=round(probability * 100, 2),
        lang=lang,
        text=text,
    )


if __name__ == "__main__":
    app.run(debug=True)
